# Generated by Django 5.1.1 on 2024-12-12 04:06
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
